controller_manager_name: /controller_manager

controller_names:
  - arm_controller

arm_controller:
  type: FollowJointTrajectory
  joints:
    - magician_joint_1
    - magician_joint_2
    - magician_joint_3
    - magician_joint_4
